### ISSUE TITLE
layout shift on certain widths when sliding

### ISSUE THREAD

**Issue by mayank99** [oddbird/oddcontrast#123]
on certain viewport widths (specifically 1066px in my case), when the ratio changes between 9.x, 10.x and 11.x, there is significant layout shift causing unpleasant flickering.

https://github.com/oddbird/oddcontrast/assets/9084735/abab9199-0301-4ce9-8541-125da1e362c0

it might help to make the ratio fixed width.

**Comment by stacyk** [comment]
I added a fix to this in PR #119  

https://github.com/oddbird/oddcontrast/pull/119/files#diff-f3707bb50b23f4dabd7f4d650bcf716a8d4d1eea35314a281c56352442a3dcb4R104

**Comment by mayank99** [comment]
awesome. i tested out the deploy preview and it seems to work!

https://github.com/oddbird/oddcontrast/assets/9084735/2fa8678a-7b87-417a-913b-924254620b34
