### ISSUE TITLE
Read info about known color issues

### ISSUE THREAD

**Issue by SondraE** [oddbird/oddcontrast#143]
## Scope

- add an unobtrusive information section that is expanded on larger screens and collapsed on smaller screen to help interested people understand the known color issues
- this section can go into as much detail as needed and even include color swatches to help people understand the foreground color issue related to alpha

## Mockups

Here are the warning-related Figma file links.
Note: I don't know why Figma is suddenly displaying green lines around various bits of the mockups, and I haven't found the way to turn that view off yet.

**Background Alpha Alert + Color Issue Info**
https://www.figma.com/file/JtQTGIpwoaOcqcWfsoeOk1/Browser-bugs-%26-other-warnings?type=design&node-id=112-2&mode=design&t=lOyosYvXrteuMN5Z-0

**Foreground Alpha Alert**
https://www.figma.com/file/JtQTGIpwoaOcqcWfsoeOk1/Browser-bugs-%26-other-warnings?type=design&node-id=12%3A348&mode=design&t=4CwzTDrU2fakSiQ4-1

**Mobile Alerts + Color Issue Info**
https://www.figma.com/file/JtQTGIpwoaOcqcWfsoeOk1/Browser-bugs-%26-other-warnings?type=design&node-id=83%3A10&mode=design&t=4CwzTDrU2fakSiQ4-1

**Mobile Alerts + Color Issue Info 2**
https://www.figma.com/file/JtQTGIpwoaOcqcWfsoeOk1/Browser-bugs-%26-other-warnings?type=design&node-id=83%3A11&mode=design&t=4CwzTDrU2fakSiQ4-1

**Comment by SondraE** [comment]
LGTM!

**Comment by jgerigmeyer** [comment]
#146 is close to merge, but it looks like this issue also includes notes about alpha in contrast ratios. Is that going to be addressed in #91 instead?

**Comment by jamesnw** [comment]
@jgerigmeyer Yes- we'll add those as part of #91.
