### ISSUE TITLE
Color browser support warning breaks layout.

### ISSUE THREAD

**Issue by jgerigmeyer** [oddbird/oddcontrast#152]
If a color format isn't supported by the user's current browser, we display a warning both at the top and in the color outputs list. Currently this warning in the outputs list breaks the layout.

Because all our color formats are supported by most modern browsers, this is easier to test locally if you temporarily change `{#if !isSupported}` to `{#if true}` in `SupportWarning.svelte`.

![Screenshot 2023-11-29 at 2 51 46 PM](https://github.com/oddbird/oddcontrast/assets/552316/9ae77b30-6e4b-4fa4-89f6-6991c90e790e)

_Originally posted by @jgerigmeyer in https://github.com/oddbird/oddcontrast/pull/145#discussion_r1409800310_

**Comment by stacyk** [comment]
@jamesnw this is ready for review
