### ISSUE TITLE
I want to share a URL to a color combination

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/oddcontrast#92]
Requested on social media:
- https://mastodon.social/@alanbsmith/110834387116274835

**Comment by SondraE** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to share a link that includes my two chosen colors.](https://trello.com/c/fxa5PQUy/52-i-want-to-share-a-link-that-includes-my-two-chosen-colors)
