### ISSUE TITLE
Warn about browser bugs in (ok)lch rendering

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/oddcontrast#95]
Requested on social media:
- https://social.vasilis.nl/@vasilis/110841553733684928

Browser bugs to track:
- [chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1440069)
- [webkit](https://bugs.webkit.org/show_bug.cgi?id=255939)
- [mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1847421)

**Comment by mirisuzanne** [comment]
I think this might be important, and we may even want to set display-p3 as the default. The current implementations of (ok)lab/lch colors are so bad, they're almost unusable. (Why did browsers ship it like this?)

**Comment by SondraE** [comment]
## Draft Proposal
https://www.figma.com/file/JtQTGIpwoaOcqcWfsoeOk1/Browser-bugs-%26-other-warnings?type=design&node-id=0%3A1&mode=design&t=RuE2m0Xo75cF0fGM-1

**Comment by SondraE** [comment]
@mirisuzanne @stacyk 
Here are the warning-related Figma file links.
Note: I don't know why Figma is suddenly displaying green lines around various bits of the mockups, and I haven't found the way to turn that view off yet.

**Out of Gamut + Format Groups**
https://www.figma.com/file/JtQTGIpwoaOcqcWfsoeOk1/Browser-bugs-%26-other-warnings?type=design&node-id=83%3A11&mode=design&t=4CwzTDrU2fakSiQ4-1

**Incorrect implementation + Expanded Color Issue Info**
https://www.figma.com/file/JtQTGIpwoaOcqcWfsoeOk1/Browser-bugs-%26-other-warnings?type=design&node-id=12%3A138&mode=design&t=4CwzTDrU2fakSiQ4-1

**Background Alpha Alert + Collapsed Color Issues**
https://www.figma.com/file/JtQTGIpwoaOcqcWfsoeOk1/Browser-bugs-%26-other-warnings?type=design&node-id=12%3A243&mode=design&t=4CwzTDrU2fakSiQ4-1

**Foreground Alpha Alert**
https://www.figma.com/file/JtQTGIpwoaOcqcWfsoeOk1/Browser-bugs-%26-other-warnings?type=design&node-id=12%3A348&mode=design&t=4CwzTDrU2fakSiQ4-1

**Mobile Alerts + Color Issue Info**
https://www.figma.com/file/JtQTGIpwoaOcqcWfsoeOk1/Browser-bugs-%26-other-warnings?type=design&node-id=83%3A10&mode=design&t=4CwzTDrU2fakSiQ4-1

**Mobile Alerts + Color Issue Info 2**
https://www.figma.com/file/JtQTGIpwoaOcqcWfsoeOk1/Browser-bugs-%26-other-warnings?type=design&node-id=83%3A11&mode=design&t=4CwzTDrU2fakSiQ4-1

**Comment by mirisuzanne** [comment]
Left some comments on the designs. It seems like we should maybe break this out into smaller stories for the specific issues and warnings.

**Comment by jamesnw** [comment]
Acceptance criteria- 

- If an unbounded color space is selected 
- And a user has a color selected that is out of gamut in the sRGB gamut
- Then, show the warning bar.

**Comment by stacyk** [comment]
I removed myself but I didn't assign anyone else (yet, wasn't sure what is left on 146, or if that matters here).

**Comment by jgerigmeyer** [comment]
@stacyk I assigned you because I think #146 is waiting for you to re-review.
